# Generated by Django 4.2.5 on 2023-11-12 18:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                ("crop_code", models.PositiveIntegerField()),
                ("crop_description", models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_start_year", models.IntegerField(null=True)),
                ("selected_end_year", models.IntegerField()),
                ("request_time", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "selected_crop",
                    models.ForeignKey(
                        db_column="selected_crop_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketdemandpredictionapp.crops",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        db_column="user_profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketdemandpredictionapp.userprofile",
                    ),
                ),
            ],
        ),
    ]
