# Generated by Django 4.2.5 on 2023-11-29 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("marketdemandpredictionapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="request_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
