# Generated by Django 4.2.5 on 2023-09-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketdemandpredictionapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crops",
            name="crop_code",
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
