# Generated by Django 4.2.5 on 2023-10-29 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("marketdemandpredictionapp", "0006_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_start_year", models.DateField()),
                ("selected_end_year", models.DateField()),
                ("request_time", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "selected_crop",
                    models.ForeignKey(
                        db_column="crop_name",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketdemandpredictionapp.crops",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        db_column="user_profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketdemandpredictionapp.userprofile",
                    ),
                ),
            ],
        ),
    ]
