# Generated by Django 4.2.5 on 2023-10-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("marketdemandpredictionapp", "0007_userpreferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="selected_crop",
            field=models.ForeignKey(
                db_column="selected_crop_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="marketdemandpredictionapp.crops",
            ),
        ),
    ]
