# Generated by Django 4.2.5 on 2023-10-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketdemandpredictionapp", "0008_alter_userpreferences_selected_crop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="selected_end_year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="selected_start_year",
            field=models.IntegerField(),
        ),
    ]
